spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deposit_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: create #create, create-drop, none, update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # set DB column name by snake case
    show-sql: true
    generate-ddl: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7ee2b750676219c7f2c7d4f1b574bf4d
            client-secret: LWMC7dvSoRq4kh7zB3QgZKRaKDRGgaT8
            client-name: Kakao
            redirect-uri: 'http://localhost:8080/login/oauth2/code/kakao'
            #
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: "id"
